version: '2'
services:

  socksproxy:
    image: weaveworks/socksproxy
    restart: always
    ports:
      - 127.0.0.1:9050:8000
    logging:
      options:
        max-size: 50m

  rabbitmq:
    image: marcelmaatkamp/rabbitmq-mqtt-ldap
    restart: always
    hostname: rabbitmq
    environment:
      RABBITMQ_NODENAME: rabbitmq@rabbitmq
    ports:
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    logging:
      options:
        max-size: 50m
        
  neo4j:
    image: neo4j
    restart: always
    ports:
     - 7473:7473
     - 7474:7474
     - 7687:7687
    volumes:
     - neo4j-data:/data
     - neo4j-logs:/logs
    environment:
     - NEO4J_AUTH=none
    logging:
      options:
        max-size: 50m
        
  steemit-live-data:
    restart: always
    image: marcelmaatkamp/steemit-amqp:latest
    environment:
     - RABBITMQ_HOSTNAME=rabbitmq
     - RABBITMQ_EXCHANGE=steemit.api
     - STEEMIT_ACCOUNT_NAME=${steemit_account_name}
     - STEEMIT_ACCOUNT_ACTIVE_KEY=${steemit_account_activekey}
    volumes:
     - ./credentials.py:/app/mycredentials.py
    extra_hosts:
     - "steemd.steemit.com:52.201.99.232"
    logging:
      options:
        max-size: 50m
      
  steemit-database:
    image: marcelmaatkamp/steemit-data-analysis-platform:1.1
    build: .
    environment:
     - logging.level.org=debug

     - spring_rabbitmq_host=rabbitmq
     - spring_rabbitmq_port=5672
     - spring_rabbitmq_username=consumer-steemit-neo4j
     - spring_rabbitmq_password=consumer-steemit-neo4j

     - spring_data_neo4j_uri=bolt://neo4j
     - spring_data_neo4j_username=neo4j
     - spring_data_neo4j_password=spring-boot-neo4j
     - spring_data_neo4j_repositories_enabled=true

     - steemit_account_name=${steemit_account_name}
     - steemit_account_postkey=${steemit_account_postkey}
     - steemit_account_activekey=${steemit_account_activekey}

    volumes:
     - steemit-database-gradle:/home/gradle/.gradle

    logging:
      options:
        max-size: 50m
        
volumes:
 neo4j-data:
 neo4j-logs:
 rabbitmq:
 steemit-database-gradle:
